landing-preview: add a shim to display `blockers` dryrun info if available (Bug 1888188)
mozilla-conduit/lando-ui pull request #198
Opened 2024-04-22 19:44 UTC by cgsheeh

As part of the checks refactor we will eventually support displaying
multiple blockers in the front end. Add a shim so Lando-UI can handle
output from before and after the refactor PR in LandoAPI is landed
and deployed.

2024-04-22 19:48 UTC, cgsheeh commented
Converting to draft as I just noticed I didn't properly cover the bases for `blocked_reason`.

2024-04-25 15:05 UTC, zzzeid requested changes
I think a simpler alternative would be to just set `blocked_reason` or `blocker` based on `revision['blocked_reasons'][0]` and `dryrun['blockers'][0]` beforehand, and that way you don't need to copy/paste the html blocks that these variables are used in.

Edit: I.e., based on similar logic in the if statements already in the templates -- and replacing usages of `dryrun['blocker']` and `revision['blocked_reason']`.

2024-04-25 18:48 UTC, cgsheeh commented
On closer inspection after deploying to dev, it looks like the code in `landing-preview.html` might be useless in the current state, since the landing preview modal can't be opened when no landing path is found due to the condition `{% elif not series or dryrun is none %}` in `stack.html`. The `revision-status.html` change seems to work as expected. We probably still want this change in `landing-preview.html` to avoid templating errors.

2024-04-26 19:05 UTC, zzzeid approved these changes

2024-04-26 19:33 UTC, merged